server:
  port: 8585
spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    cache-names:
      - cache1
      - cache2
    redis:
      time-to-live: 60000
      cache-null-values: true
  application:
    name: CUSTOMER-SERVICE
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:4545
  datasource:
    url: jdbc:mysql://localhost:3306/user
