server:
  port: 6565
spring:
  application:
    name: ADMIN-SERVICE
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:4545
  datasource:
    url: jdbc:mysql://localhost:3306/admin