server:
  port: 4545
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cdacproject786/microservice-config
          clone-on-start: true
